native def get(url: str) -> (int, str)
native def get(url: str, timeout_ms: int) -> (int, str)
native def get(url: str, headers: dict[str, str]) -> (int, str)
native def get_response_headers(url: str) -> (int, str, list[(str, str)])
native def post(url: str, body: str) -> (int, str)
native def post(url: str, body: str, timeout_ms: int) -> (int, str)
native def post(url: str, body: str, headers: dict[str, str]) -> (int, str)
native def post_response_headers(url: str, body: str) -> (int, str, list[(str, str)])
