typedef enum {
    TOKEN_KEYWORD,
    TOKEN_IDENTIFIER,
    TOKEN_SYMBOL,
    TOKEN_NUMBER,
    TOKEN_OPERATOR,
    TOKEN_ASSIGN,
    TOKEN_PLUS, TOKEN_MINUS,
    TOKEN_PUNCT,
    TOKEN_COLON,
    TOKEN_UNKNOWN,
    TOKEN_INDENT,
    TOKEN_DEDENT,
    TOKEN_NEWLINE,
    TOKEN_LPAREN, TOKEN_RPAREN,
    TOKEN_RARROW,
    TOKEN_EOF
} TokenType;

typedef struct {
    TokenType type;
    char value[64];
} Token;